name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  dagger:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Dagger
        run: curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=v0.18.10 BIN_DIR=/usr/local/bin sh

      - uses: dagger/dagger-for-github@v5
        with:
          cmds: lint,test
